### ISSUE TITLE
Does this a sidebar when menu is clicked?

### ISSUE THREAD

**Issue by jrote1** [thosakwe/material_toolbar#1]

**Comment by thosakwe** [comment]
No. Currently working on a [menu](https://github.com/thosakwe/material_menu) component, and then I'll work on a sidenav.

In the meantime...

```html
<material-toolbar icon="menu" (iconClick)="toggleSidenav()"></material-toolbar>
```

**Comment by thosakwe** [comment]
@jrote1 https://github.com/thosakwe/material_sidenav
